version: '3.9'
services:
  chatgpt-midjourney:
    profiles: ["no-proxy"]
    container_name: chatgpt-midjourney
    image: licoy/chatgpt-midjourney
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - CODE=$CODE
      - BASE_URL=$BASE_URL
      - OPENAI_ORG_ID=$OPENAI_ORG_ID
      - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
      - DISABLE_GPT4=$DISABLE_GPT4

  midjourney-proxy:
    container_name: midjourney-proxy
    image: novicezk/midjourney-proxy
    ports:
      - 8080:8080
    restart: unless-stopped
